### PR TITLE
Eval app improvements

### PR DESCRIPTION
**Pull request by guillaume-millot**
This PR contains the following fixes and improvements:

- Updated yaml configuration file with more relevant extraction methodologies to benchmark
- Added try catch in unstructured API to prevent Python error in case no table was extracted
- Updated eval README and moved data files to run streamlit app to `eval/data/` folder to get started more easily
- Added eval dependencies to poetry
- Eval app improvements (see below)

Eval app improvements

- Moved PDF and REF data from right to left tabs for better clarity
- New PDF viewer allowing to zoom in/out
- Display message when no table got extracted
- Fixed display issue for dataframes with multi-row headers (convert header to single row)
- Fixed display issue for dataframes with empty headers (fill empty header)
- Help tips added

### CODE REVIEW

**Review by kaaloo — CHANGES_REQUESTED** [review]
Amazing work!  You have some pre-commit issues and failing tests to check out.

Don't forget to [install the pre-commit git hooks](https://pre-commit.com/#3-install-the-git-hook-scripts) so that you technically can't commit to git before fixing this type of issue.

I don't think it hurts to add the extra dependencies for the streamlit app directly in poetry.  The eval app is part of the project after all and it's a bit painful to have to remember additional steps.  I would also merge the eval README with the main README .  The eval app should be a first class citizen IMHO.

image

**Comment by kaaloo** [comment]
Also @guillaume-millot does it make sense to check the files you sent me by slack in the repo in some well known location for the eval app?  It would make it easier for someone to get started.

**Comment by guillaume-millot** [comment]
> Amazing work! You have some pre-commit issues and failing tests to check out.
> 
> Don't forget to [install the pre-commit git hooks](https://pre-commit.com/#3-install-the-git-hook-scripts) so that you technically can't commit to git before fixing this type of issue.

There are 2 precommit issues:

1. Test test/test_pdf_downloader.py::TestCBCRScript::test_download_pdf is failing. It seems the issue got introduced by this commit https://github.com/dataforgoodfr/12_taxobservatory/commit/ef3106348cdf817ed47d21ef22ecf4bbd3cd75f8
2. Vulnerability found in langchain version 0.1.16

> I don't think it hurts to add the extra dependencies for the streamlit app directly in poetry.
Ok I'll do that before merging.

> I would also merge the eval README with the main README . The eval app should be a first class citizen IMHO.
Great point, but the main README currently is already really long. Let's keep this in mind for the future?

> Also @guillaume-millot does it make sense to check the files you sent me by slack in the repo in some well known location for the eval app?
Ok

**Comment by kaaloo** [comment]
> There are 2 precommit issues:
> 
> 1. Test `test_pdf_downloader.py::TestCBCRScript::test_download_pdf` is failing. It seems the issue got introduced by commit [ef31063](https://github.com/dataforgoodfr/12_taxobservatory/commit/ef3106348cdf817ed47d21ef22ecf4bbd3cd75f8)
> 2. Vulnerability found in langchain version 0.1.16
> 
> @kaaloo would you know how to fix 2? Re: 1, I'll create an issue so it can be fixed separately if you're ok with that!
> 

@guillaume-millot  since these are pre-commit issues, you will have to skip the failing test by adding a [pytest skip decorator](https://docs.pytest.org/en/8.0.x/how-to/skipping.html#skipping-test-functions).  You can see if updating langchain fixes the vulnerability:

```
poetry add langchain@latest
```

**Comment by guillaume-millot** [comment]
I skipped the test and will create an issue.
Running `poetry add langchain@latest` bumped langchain version to 0.1.17 but the vulnerabilities are still there :(

I added the missing dependencies to poetry and moved the REF CSV & sample pickle file to a new `eval/data` directory to make it easier to get started (great suggestion!).

@kaaloo are you ok to merge?

**Review by kaaloo — APPROVED** [review]
Looks good let's leave the vulnerability warning visible then.  We can always ignore it if it's not relevant to our use of langchain by updating `.pre-commit-config.yaml` (see https://github.com/Lucas-C/pre-commit-hooks-safety):

```
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
      - id: python-safety-dependencies-check
        args: ["--ignore=66962"]
```

**Comment by guillaume-millot** [comment]
I've just added `args: ["--ignore=66962"]` per our conversation on slack.

**Pull request merged**
